# Generated by Django 3.0.8 on 2020-08-03 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date de la capture')),
                ('mac_address', models.TextField(max_length=20, verbose_name='Adresse MAC')),
                ('signal_strength', models.IntegerField(blank=True, verbose_name='Puissance du signal')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
        ),
    ]
