# Generated by Django 3.0.8 on 2020-08-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerberus_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detecteddevices',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de la capture'),
        ),
    ]
